# Generated by Django 4.1.3 on 2023-03-24 16:46

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'Genre',
                'ordering': ('-created_timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('track', models.FileField(blank=True, upload_to='tracks', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3'])])),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, upload_to='track_arts', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(blank=True, to='tracks.genre')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'db_table': 'Tracks',
                'ordering': ('-created_timestamp',),
            },
        ),
    ]
