# Generated by Django 4.1.3 on 2023-03-24 16:46

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='contacts_icons', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])])),
                ('active', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='contact_image', validators=[django.core.validators.FileExtensionValidator(['jpg'])])),
                ('header', models.CharField(blank=True, max_length=75)),
                ('body', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'ContactText',
                'verbose_name_plural': 'ContactText',
                'ordering': ['-id'],
            },
        ),
    ]
