# Generated by Django 4.1.3 on 2023-03-24 16:46

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=200)),
                ('transanction_id', models.CharField(max_length=55)),
                ('transanction_message', models.CharField(max_length=255)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='support_images', validators=[django.core.validators.FileExtensionValidator(['jpg'])])),
                ('header', models.CharField(blank=True, max_length=75)),
                ('body', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Support Me',
                'verbose_name_plural': 'Support Me',
                'ordering': ['-id'],
            },
        ),
    ]
