# Generated by Django 4.1.3 on 2023-03-24 16:46

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='about_images', validators=[django.core.validators.FileExtensionValidator(['jpg'])])),
                ('header', models.CharField(max_length=75)),
                ('body', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
                'ordering': ['-id'],
            },
        ),
    ]
