# Generated by Django 4.1.3 on 2023-03-24 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('description', tinymce.models.HTMLField()),
                ('logo', models.ImageField(blank=True, upload_to='hero_logo', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('explore_button_text', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
                'db_table': 'Hero',
                'ordering': ('created_timestamp',),
            },
        ),
        migrations.CreateModel(
            name='HeroImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images', validators=[django.core.validators.FileExtensionValidator(['jpg'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_timestamp', models.DateTimeField(auto_now=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.hero')),
            ],
            options={
                'verbose_name': 'HeroImage',
                'verbose_name_plural': 'HeroImages',
                'db_table': 'HeroImage',
                'ordering': ('created_timestamp',),
            },
        ),
    ]
